// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://apxlooxhgiaenczbfume.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFweGxvb3hoZ2lhZW5jemJmdW1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MzEyODMsImV4cCI6MjA3MDAwNzI4M30.T3xaPBclc1MosbmdW0aANb3_LXsGfEJX_lQ7xzwk-fk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});